<?php $menuHelper = Mage::helper('megamenu'); ?>
<?php $menuData = $menuHelper->getMenuData(); extract($menuData); ?>
<div class="vmegamenu block">
    <div class="block-title"><strong><?php echo $this->__('Categories') ?></strong></div>
    <div class="block-content clearfix">
        <ul class="nav-category-list visible-md visible-lg">
            <?php echo $menuHelper->getSideCategoryList(); ?>
        </ul>
        <div class="mobile-cat-list category-accordion-wrapper home-sidebar-accordion accordion-format hidden-md hidden-lg">
            <?php echo $menuHelper->getCategoryMobileItem(); ?>
        </div>
    </div>
</div>