<?php $menuHelper = Mage::helper('megamenu'); ?>
<?php $menuData = $menuHelper->getMenuData(); extract($menuData); ?>
<div class="header-wrapper">
    <div class="main-nav visible-md visible-lg">
        <div class="menu-wrapper">
            <div class="menu-all-pages-container">
                <?php if(Mage::getStoreConfig('granada_setting/header_settings/header_main_type') == 'top_main_type_3'):?>
                    <?php /** granada header type 3 **/ ?>
                    <ul class="menu left-menu">
                        <?php echo $menuHelper->getMenuContent('left'); ?>
                    </ul>
                    <ul class="menu right-menu">
                        <?php echo $menuHelper->getMenuContent('right'); ?>
                    </ul>
                <?php else: ?>
                    <ul class="menu">
                        <?php echo $menuHelper->getMenuContent('all'); ?>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
var SW_MENU_POPUP_WIDTH = <?php echo $_popupWidth; ?>;
//]]>
</script>