<?php
    $productId = $this->get_ProductId();
    $_product = Mage::getModel('catalog/product')->load($productId);
    $_helper = $this->helper('catalog/output');
    $_grhelper =  Mage::helper('granada');
?>
<?php if($_product->getId()): ?>
<div class="show-case" data-posx="<?php echo $this->getIconXPosition()?>" data-posy="<?php echo $this->getIconYPosition()?>" data-productpos="<?php echo $this->getPopDirection()?>" data-productid="<?php echo $productId ?>">
    <a href="<?php echo $_product->getProductUrl() ?>" class="button button-custom button-white show-icon">icon</a>
    <div class="pop-product" id="<?php echo $productId ?>">
        <?php if ($_grhelper->isKeepRatio()):?>
            <img src="<?php echo Mage::helper('catalog/image')->init($_product,'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(200); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        <?php else: ?>
            <?php $imgWidth = 200; ?>
            <?php $imgHeight = 200 * $_grhelper->getImgHeight()/$_grhelper->getImgWidth(); ?>
            <img src="<?php echo Mage::helper('catalog/image')->init($_product,'small_image')->resize($imgWidth, $imgHeight); ?>" width="<?php echo $imgWidth ?>" height="<?php echo $imgHeight ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        <?php endif; ?>
        <?php echo $this->getPriceHtml($_product, true) ?>
        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
        <a href="<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>" class="button pop-cart-button"><?php echo 'add to cart'?></a>
    </div>
</div>
<?php else: ?>
<div class="pop-product" id="<?php echo $productId ?>">
    <?php echo $this->__('There is no matched product.') ?>
</div>
<?php endif; ?>