<?php
$productId = $this->get_ProductId();
$_product = Mage::getModel('catalog/product')->load($productId);
$_helper = $this->helper('catalog/output');
$_grhelper =  Mage::helper('granada');
?>
<?php if($_product->getId()): ?>
    <div class="banner hover-zoom black-bg banner-product full-inner">
        <div class="banner-content">
            <div class="banner-inner vertical-bottom">
				<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions-wrapper">
                    <a href="<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>" class="button"><?php echo 'add to cart'?></a>
                    <div class="links-wrapper">
                        <?php if (Mage::helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo Mage::helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="button link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
                        <?php if($_compareUrl=Mage::helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="button link-compare"><?php echo $this->__('Add to Compare') ?></a>
                        <?php endif; ?>
                    </div>
                </div>

            </div>
        </div>
        <?php if ($_grhelper->isKeepRatio()):?>
            <img src="<?php echo Mage::helper('catalog/image')->init($_product,'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(370); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        <?php else: ?>
            <?php $imgWidth = 370; ?>
            <?php $imgHeight = 370 * $_grhelper->getImgHeight()/$_grhelper->getImgWidth(); ?>
            <img src="<?php echo Mage::helper('catalog/image')->init($_product,'small_image')->resize($imgWidth, $imgHeight); ?>" width="<?php echo $imgWidth ?>" height="<?php echo $imgHeight ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        <?php endif; ?>
    </div>
<?php else: ?>
    <div class="pop-product" id="<?php echo $productId ?>">
        <?php echo $this->__('There is no matched product.') ?>
    </div>
<?php endif; ?>