<?php
$store = Mage::app()->getStore();
$code = $store->getCode();
$enabled = Mage::getStoreConfig('granada_setting/slider_settings/s_slider_enable', $code);
$static_block_id = Mage::getStoreConfig('granada_setting/slider_settings/b_slider_id', $code);
if($enabled == 1){
    ?>
    <div id="slideshow">
        <?php
        echo $this->getLayout()->createBlock('cms/block')->setBlockId($static_block_id)->toHtml();
        ?>
    </div>
<?php
} else {
    ?>
<?php
}
?>