<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $_grhelper = Mage::helper('granada');
    if ($_grhelper->getBannerStyle($code) == 'full') {
        $_helper    = $this->helper('catalog/output');
        $_category  = $this->getCurrentCategory();
        $_imgHtml   = '';
        $_imgUrl = $_category->getImageUrl();
        $banner_id = $_grhelper->getCategoryBannerBlock();    
        if ($banner_id) {
            $banner_block = Mage::getModel('cms/block')->load($banner_id);        
            if($banner_block->getIsActive()){
                $_imgHtml = '<div class="container"><div class="category-banner-block">'.$this->getLayout()->createBlock('cms/block')->setBlockId($banner_id)->toHtml().'</div></div>';
            } else if($_imgUrl){
                $_imgHtml = '<div class="container"><p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p></div>';
                $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
            }
        } else if ($_imgUrl) {
            $_imgHtml = '<div class="container"><p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p></div>';
            $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        }                
        echo $_imgHtml;
    }
?>