<?php
$socialfeeds = $this->helper('socialfeeds');

$fb_result = $socialfeeds->getFBFans();
if ($fb_result) : ?>
<?php
$fb_profile = $fb_result['profile'];
$fb_fans = $fb_result['fans'];
$fb_limit = $fb_result['limit'];
?>
<div class="block-facebook-like ">
    <h3 class="footer-title facebook-title"><?php echo $this->__('Facebook') ?></h3>
    <div class="fb-like-btn footer-button"><a target="_blank" href="<?php echo $fb_profile['link'] ?>" title="<?php echo $fb_profile['name'] ?>"><?php echo $this->__('Like') ?>!</a> </div>

    <div class="block-content">
        <p class="like-text"><?php echo $fb_profile['likes'] ?> <?php echo $this->__('people like') ?> <a target="_blank" href="<?php echo $fb_profile['link'] ?>" title="<?php echo $fb_profile['name'] ?>"><?php echo $fb_profile['name'] ?></a></p>
        <div class="clearfix fb-persons">
            <?php echo $fb_fans ?>
        </div>
    </div>
<?php endif; ?>

</div>                