<?php
/**
 * Product list template (For footer)
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $img_width = 115;
    $img_height = 146;
    if (!Mage::getStoreConfig('granada_setting/footer_settings/aspect_ratio', $code)) {
        if(Mage::getStoreConfig('granada_setting/footer_settings/ratio_width', $code))
            $img_width = Mage::getStoreConfig('granada_setting/footer_settings/ratio_width',$code);

        if(Mage::getStoreConfig('granada_setting/footer_settings/ratio_height',$code))
            $img_height = Mage::getStoreConfig('granada_setting/footer_settings/ratio_height',$code);
    }
?>
<?php if(!$_productCollection->count()): ?>
<p><?php echo $this->__('There are no products.')?></p>
<?php else: ?>
    <ul class="footer-products-list">
        <?php foreach ($_productCollection as $_product): ?>
            <li>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                    <img src="<?php if(Mage::getStoreConfig('granada_setting/footer_settings/aspect_ratio', $code)):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(115); ?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($img_width, $img_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="<?php echo $img_width ?>" height="<?php echo $img_height ?>" />
                    <?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>
                </a>
                <?php echo $this->getReviewsSummaryHtml($_product,'short') ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>