<?php /**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.zeonsolutions.com/shop/license-enterprise.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento ENTERPRISE edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    base_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://www.zeonsolutions.com/shop/license-enterprise.txt
 */ ?>
<?php $_manufacturersCollection = $this->getManufacturersCollection(); ?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Brands') ?></span></strong>
    </div>
    <?php $_i = 0; $class=""; ?>
    <div class="block-content">
        <ul class="manufacturers_list">
            <?php foreach ($_manufacturersCollection as $_manufacturer): ?>
                <li>					
                    <?php $_i++; if($_i == count($_manufacturersCollection)) $class="last"; ?>					
                    <a href="<?php echo $this->getUrl('manufacturers' . '/' . $_manufacturer->getIdentifier()) ?>" class="<?php echo $class; ?>"><?php echo $this->__($_manufacturer->getManufacturer()) ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>