<?php
$products = $this->getRecentProducts();
?>
<div class="product_list_item">
  <?php if (is_array($products) && count($products)) { 
        $i=0;
        foreach($products as $product) { 
         $i++; ?>
         <div class="recent_product imgage<?php echo $i ?>">
            <a href="<?php echo $product['url'] ?>"><img src="<?php echo $product['thumbnailUrl'] ?>" alt="<?php echo $product['name'] ?> kopen"></a>
            <?php if ($product['showTitle'] == true): ?><div class="title"><a href="<?php echo $product['url'] ?>"><?php echo $product['name']?></a></div><?php endif; ?>
            <span class="price"><?php echo $product['price'] ?></span>
         </div>
   <?php } ?>
  <?php } ?>
</div>
