<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?> 
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?> 
</div>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
		<div class="postLeft">
			<div class="post-date-icon">
				<div class="posted-on"></div>
				<div class="post-date">
					<?php echo $post->getDay()." ".$post->getMonthShort(); ?>
				</div>
			</div>
			<?php if ($this->getCommentsEnabled()): ?>
			<div class="post-comment-icon">
				<div class="comment-icon"></div>
				<div class="comment-count">
					<?php 
						$com_count = ($post->getCommentCount())?$post->getCommentCount():0;
						echo $com_count." ".$this->__("Com"); 
					?>
				</div>
			</div>
			<?php endif; ?>
		</div>
		<div class="postRight">
			<div class="postBanner">
				<?php
					if($banner_image = $post->getBanner()){
				?>
					<a href="<?php echo $post->getAddress(); ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$banner_image; ?>" alt=""/></a>
					
				<div class="blog-mask">
					<div class="mask-content">
						<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$banner_image; ?>" class="post-banner-lightbox">
							<i class="icon-resize-full"></i>
						</a>
						<a href="<?php echo $post->getAddress(); ?>" class="post-banner-link">
							<i class="icon-link"></i>
						</a>
					</div>
				</div>
				<?php } ?>
			</div>
			<h3 class="post-title">
				<a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
			</h3>
			<div class="postContent"><?php echo $post->getPostContent(); ?></div>
			<div class="post-info">
				<span class="posted-by"><?php echo $this->__('By')?>&nbsp;<strong><?php echo $post->getUser() ?></strong></span>&nbsp;/
				<?php $postCats = $post->getCats(); ?>
				<?php if (!empty($postCats)): ?>
				<span class="posted-in">
					<?php $_i = 0; ?>
					<?php foreach ($postCats as $data): ?>
						<a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a><span class="<?php echo ($_i == count($postCats)-1)?'last':''; ?>">,</span>
						<?php $_i++; ?>
					<?php endforeach; ?>
				</span>
				<?php endif; ?>
			</div>
			<div class="clearer"></div>
			<?php echo $this->getBookmarkHtml($post) ?>        
		</div>
    </div>
<?php endforeach; ?> 
<?php echo $this->getChildHtml('smartwave_blog_comments_toolbar'); ?>
