<div class="lastest-post">
	<h3 class="title a-left"><span><?php echo $this->__('Lastest Posts')?></span></h4>
	<div>
		<?php $posts = $this->getRecent() ?>
		<?php if (count($posts)): ?>
			<?php foreach ($posts as $post): ?>
			<div class="row">
				<?php
					if($banner_image = $post->getBanner()){
				?>
				<div class="col-sm-6">
					<div class="postBanner">
							<a href="<?php echo $post->getAddress(); ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$banner_image; ?>" alt=""/></a>
							
						<div class="blog-mask">
							<div class="mask-content">
								<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$banner_image; ?>" class="post-banner-lightbox">
									<i class="icon-resize-full"></i>
								</a>
								<a href="<?php echo $post->getAddress(); ?>" class="post-banner-link">
									<i class="icon-link"></i>
								</a>
							</div>
						</div>

					</div>
				</div>
				<?php } ?>
				<div class="col-sm-6">
					<h4 class="post-title">
						<a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
					</h4>
					<div class="post-info">
						<span class="posted-on"><?php echo $this->__('Posted on ')?><?php echo $post->getCreatedTime(); ?></span>
						<span class="posted-by"><?php echo $this->__('by')?>&nbsp;<strong><?php echo $post->getUser() ?></strong></span>
					</div>
					<div class="postContent"><?php echo $post->getShortContent(); ?></div>
					<a href="<?php echo $post->getAddress(); ?>" class="button read-more"><?php echo $this->__('Read More') ?></a>
				</div>
			</div>
			<?php endforeach; ?>
		<?php else: ?>                
			<?php echo $this->__('There is no recent posts.'); ?>
		<?php endif; ?>
	</div>
</div>