<div class="slider-blog-container">	
	<div class="more-title">
		<h2 class="title sub-title"><span><?php echo $this->__('From The Blog') ?></span></h2>
	</div>
	<?php $posts = $this->getRecent() ?>
	<?php if (count($posts)): ?>
    <div class="row">
        <div class="items-slider posts-slider blog-home-type-1 blog-slider-type-1">
            <?php foreach ($posts as $post): ?>
            <div class="slide-item post-slide">
                <div class="post-info-container">
                    <div class="post-information">
                        <span class="posted-on"><?php echo date('d M', strtotime($post->getCreatedTime())) ?></span>
                    </div>
                    <?php if($post->getCommentCount()): ?>
                        <div class="post-comment-count"><?php echo $post->getCommentCount().$this->__(' Com'); ?></div>
                    <?php else: ?>
                        <div class="post-comment-count"><?php echo $post->getCommentCount().$this->__('0 Com'); ?></div>
                    <?php endif; ?>
                </div>
                <div class="post-content-container">
                    <?php
                        if($banner_image = $post->getBanner()){
                    ?>
                    <div class="post-images">
                        <a href="<?php echo $post->getAddress(); ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$banner_image; ?>" alt=""/></a>
                    </div>
                    <?php } ?>
                    <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                    <div class="postContent"><?php echo $post->getShortContent(); ?></div>
                    <a href="<?php echo $post->getAddress(); ?>" class="button button-custom button-custom-active"><?php echo $this->__('Read More') ?></a>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
     </div>
	<script type="text/javascript">
	//<![CDATA[
		jQuery('.slider-blog-container .blog-home-type-1').owlCarousel({
			items: 2,
			itemsDesktop: [1199, 2],
			itemsDesktopSmall: [991, 2],
			itemsTablet: [768, 1],
			itemsMobile: [479, 1],
			lazyLoad: true,
			pagination: false,
			navigation: true
		});
	//]]>
	</script>
	<?php else: ?>
	<div class="content-element">
		<div class="note-msg"><span class="msg-content"><?php echo $this->__('There are no blogs.') ?></span></div>
	</div>
	<?php endif; ?>
</div>
