<div class="slider-blog-container">	
<?php $posts = $this->getRecent() ?>
	<div class="block-title">
		<strong>From Blog</strong>
		<?php if (count($posts)> 3): ?>
		<div class="arrows-container">
			<div class="button button-custom button-custom-active arrows-left blog-arrows-left button-white"></div>
			<div class="button button-custom button-custom-active arrows-right blog-arrows-right button-white"></div>
		</div>
		<?php endif; ?>
	</div>	
	<?php if (count($posts)): ?>
	<?php $_i = 0; ?>
	<div class="block-content">
		<div class="row">
			<div class="items-slider posts-slider side-blog-type-2 blog-slider-type-2">
				<?php foreach ($posts as $post): ?>
				<?php if($_i%3 == 0): ?>
				<div class="blog-item">
				<?php endif; ?>
				<div class="slide-item post-slide">			
					<div class="post-info-vertical-container">
						<div class="post-information">
							<span class="posted-on"><?php echo date('d M', strtotime($post->getCreatedTime())) ?></span>
						</div>
					</div>
					<div class="post-content-container">                    
						<h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
					</div>			
				</div>
				<?php if($_i%3 == 2 || $_i == count($posts) - 1): ?>
					</div>
				<?php endif; ?>
				<?php $_i++; ?>
				<?php endforeach; ?>
			</div>
		 </div>
	 </div>
	<script type="text/javascript">
	//<![CDATA[
		var blog_side_custom = jQuery('.slider-blog-container .side-blog-type-2').owlCarousel({
			items: 1,
			itemsDesktop: [1199, 1],
			itemsDesktopSmall: [991, 1],
			itemsTablet: [768, 1],
			itemsMobile: [479, 1],
			lazyLoad: true,
			pagination: false,
			navigation: false
		});
		jQuery('.blog-arrows-left').on('click', function(){
			blog_side_custom.trigger('owl.prev');
		});
		jQuery('.blog-arrows-right').on('click', function(){
			blog_side_custom.trigger('owl.next');
		});
	//]]>
	</script>
	<?php else: ?>
	<div class="content-element">
		<div class="note-msg"><span class="msg-content"><?php echo $this->__('There are no blogs.') ?></span></div>
	</div>
	<?php endif; ?>
</div>
