<?php $_code = $this->getMethodCode() ?>

<div id="payment-errors" class="validation-advice" style="display:none;"></div>
<fieldset class="form-list buckaroo-method">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none" class="buckaroo3extended_input">
        <li>
            <label for="<?php echo $_code;?>_BPE_Customergender" class="required"><?php echo $this->__('Salutation');?>: <em>*</em></label>
            <div class="input-box">
                <select name="<?php echo $_code;?>_BPE_Customergender" class="validate-select validate-number" title="<?php echo $this->__('Salutation');?>" id="<?php echo $_code;?>_BPE_Customergender">
                    <option value=''><?php echo $this->__('Select'); ?></option>
                    <option value="1" <?php echo ($this->getGender()===1)?'selected':'';?>><?php echo $this->__('Mr.'); ?></option>
                    <option value="2" <?php echo ($this->getGender()===2)?'selected':'';?>><?php echo $this->__('Mrs.'); ?></option>
                </select>
            </div>
        </li>
        <li>
            <label><?php echo $this->__('Billing name');?>:</label>
            <div class="input-box">
                <span class="disabled stylefix" id="<?php echo $_code;?>_BPE_Customername" title="<?php echo $this->__('Name');?>"><?php echo $this->getName(); ?></span>
            </div>
        </li>
        <li <?php if ($this->getAddress()->getTelephone() && $this->getAddress()->getTelephone() != '-'): ?>style="display:none;"<?php endif; ?>>
            <label class="required" for="<?php echo $_code;?>_BPE_Customerphone"><?php echo $this->__('Telephone') ?>: <em>*</em></label>
            <div class="input-box">
                <input class="input-text required-entry" type="text" title="<?php echo $this->__('Telephone') ?>" name="<?php echo $_code;?>_bpe_customer_phone_number" value="<?php echo $this->getPhoneNumber(); ?>"  id="<?php echo $_code;?>_BPE_Customerphone"/>
            </div>
        </li>
        <li>
            <?php
            echo $this->getLayout()->createBlock('buckaroo3extended/customer_widget_dob')
                ->setFieldIdFormat($_code . ':billing:%s')
                ->setFieldNameFormat('payment[' . $_code . '][%s]')
                ->setIsRequired(true)
                ->setPaymentMethodCode($_code)
                ->setDate($this->getCustomer()->getDob())
                ->toHtml();
            ?>
        </li>

        <?php if($this->getPaymethod() == 'afterpayacceptgiro'):?>
            <li>
                <label for="<?php echo $_code;?>_BPE_customer_account_number" class="required"><?php echo $this->__('Bank account number') ?>: <em>*</em></label>
                <div class="input-box">
                    <input class="input-text required-entry" type="text" title="<?php echo $this->__('Bank account number') ?>" name="<?php echo $_code;?>_bpe_customer_account_number" value="<?php echo $this->getBankAccount(); ?>" id="<?php echo $_code;?>_BPE_customer_account_number" />
                </div>
            </li>
        <?php endif;?>


        <?php $currentBusiness = $this->getBusiness(); ?>

        <?php $currentBusiness = ($this->getPaymethod() == 'afterpaydigiaccept')? $currentBusiness : '1'; ?>

        <?php if($currentBusiness == '1'): ?>

            <li>
                <input type="hidden" name="<?php echo $_code;?>_BPE_BusinessSelect" value="1" id="<?php echo $_code;?>_BPE_BusinessSelect"/>
            </li>

        <?php elseif($currentBusiness == '2'):?>

            <li>
                <input type="hidden" name="<?php echo $_code;?>_BPE_BusinessSelect" value="2" id="<?php echo $_code;?>_BPE_BusinessSelect"/>
                <div id="b2b-fields">
                    <label class="required" for="<?php echo $_code;?>_BPE_CompanyCOCRegistration"><?php echo $this->__('COC Number');?></label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text" name="<?php echo $_code;?>_BPE_CompanyCOCRegistration" id="<?php echo $_code;?>_BPE_CompanyCOCRegistration" value="<?php echo $this->getCompanyCOCRegistration();?>" />
                    </div>
                    <label class="required" for="<?php echo $_code;?>_BPE_CompanyName"><?php echo $this->__('Company Name');?></label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text" name="<?php echo $_code;?>_BPE_CompanyName" id="<?php echo $_code;?>_BPE_CompanyName" value="<?php echo $this->getCompanyName();?>" />
                    </div>
                    <label class="required" for="<?php echo $_code;?>_BPE_CostCentre"><?php echo $this->__('Cost Center');?></label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text" name="<?php echo $_code;?>_BPE_CostCentre" id="<?php echo $_code;?>_BPE_CostCentre" value="<?php echo $this->getCostCentre();?>" />
                    </div>
                    <label class="required" for="<?php echo $_code;?>_BPE_VatNumber"><?php echo $this->__('VAT Number');?></label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text" name="<?php echo $_code;?>_BPE_VatNumber" id="<?php echo $_code;?>_BPE_VatNumber" value="<?php echo $this->getVatNumber();?>" />
                    </div>
                </div>
            </li>

        <?php elseif($currentBusiness == '3'):?>

            <li>
                <label for="<?php echo $_code;?>_BPE_BusinessSelect"><?php echo $this->__('Set Business');?>:</label>
                <div class="input-box">
                    <select name="<?php echo $_code;?>_BPE_BusinessSelect" class="validate-select validate-number" title="<?php echo $this->__('Set Business');?>" id="<?php echo $_code;?>_BPE_BusinessSelect">
                        <option value="1" <?php echo (($this->getBusinessSelect()=='1')?'selected':'') ;?>><?php echo $this->__('B2C');?></option>
                        <option value="2" <?php echo (($this->getBusinessSelect()=='2')?'selected':'') ;?>><?php echo $this->__('B2B');?></option>
                    </select>
                </div>
                <?php
                $style = '';
                if(is_null($this->getBusinessSelect()) || $this->getBusinessSelect() == '1'){
                    $style = ' style="display:none;"';
                }
                ?>
                <div id="b2b-fields"<?php echo $style;?>>
                    <label class="required" for="<?php echo $_code;?>_BPE_CompanyCOCRegistration"><?php echo $this->__('COC Number');?></label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text" name="<?php echo $_code;?>_BPE_CompanyCOCRegistration" id="<?php echo $_code;?>_BPE_CompanyCOCRegistration" value="<?php echo $this->getCompanyCoCRegistration();?>" />
                    </div>
                    <label class="required" for="<?php echo $_code;?>_BPE_CompanyName"><?php echo $this->__('Company Name');?></label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text" name="<?php echo $_code;?>_BPE_CompanyName" id="<?php echo $_code;?>_BPE_CompanyName" value="<?php echo $this->getCompanyName();?>" />
                    </div>
                    <label class="required" for="<?php echo $_code;?>_BPE_CostCentre"><?php echo $this->__('Cost Center');?></label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text" name="<?php echo $_code;?>_BPE_CostCentre" id="<?php echo $_code;?>_BPE_CostCentre" value="<?php echo $this->getCostCentre();?>" />
                    </div>
                    <label class="required" for="<?php echo $_code;?>_BPE_VatNumber"><?php echo $this->__('VAT Number');?></label>
                    <div class="input-box">
                        <input class="input-text required-entry" type="text" name="<?php echo $_code;?>_BPE_VatNumber" id="<?php echo $_code;?>_BPE_VatNumber" value="<?php echo $this->getVatNumber();?>" />
                    </div>
                </div>
            </li>

        <?php endif; ?>

        <li class="tac-accept">
            <div class="input-box">
                <input class="input-checkbox required-entry" type="checkbox" title="<?php echo $this->__('Terms and Conditions') ?>" name="<?php echo $_code;?>_bpe_accept" value="checked" id="<?php echo $_code;?>_BPE_terms_and_conditions" />
            </div>
            <label for="<?php echo $_code;?>_BPE_terms_and_conditions" class="required">
                <?php echo $this->__('Yes, I accept the %sterms and condition%s for the use of Afterpay.', '<a style="float:none;margin:0;" target="_blank" href="https://www.afterpay.nl/nl/klantenservice/betalingsvoorwaarden/">', '</a>') ?> <em>*</em>
            </label>
        </li>

        <li>
            <?php echo Mage::helper('buckaroo3extended')->__('Please make sure all fields are filled in correctly before proceeding.')?>
        </li>
    </ul>
</fieldset>
<script type="text/javascript">
    var paymentCode = '<?php echo $_code;?>';

    $(paymentCode + '_BPE_BusinessSelect').observe('change', function(event){
        if($(paymentCode + '_BPE_BusinessSelect').getValue() == 2){
            $('b2b-fields').show();
        }

        if($(paymentCode + '_BPE_BusinessSelect').getValue() == 1){
            $('b2b-fields').hide();
        }
    });
</script>

