<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
$_latitude = Mage::getStoreConfig('granada_setting/google_map/latitude', $code);
$_longitude = Mage::getStoreConfig('granada_setting/google_map/longitude', $code);
$_zoom = Mage::getStoreConfig('granada_setting/google_map/zoom', $code);
$_marker_image = Mage::getStoreConfig('granada_setting/google_map/marker_image', $code);
if (!$_marker_image) {
    $_marker_image = 'pin.png';
}
?>

<div id="google_map"></div>
<script src="//maps.google.com/maps/api/js?sensor=false&amp;v=3.17"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/maplabel.js"></script>
<script>
    /*---- Google map -----*/
    (function () {
        "use strict";
        function initialize() {
            jQuery.noConflict();
            "use strict";
            /* change your with your coordinates */
            var myLatLng = new google.maps.LatLng(<?php echo $_latitude ?>, <?php echo $_longitude ?>), // Your coordinates
                mappy = {
                    center: myLatLng,
                    zoom: <?php echo $_zoom ?>,
                    zoomControl:true,
                    mapTypeControl:true,
                    scaleControl:true,
                    scrollwheel: false,
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    styles: [//Style for map
                        {
                            "featureType": "landscape",
                            "stylers": [
                                {
                                    "saturation": -100
                                },
                                {
                                    "lightness": 25
                                },
                                {
                                    "visibility": "on"
                                }
                            ]
                        },
                        {
                            "featureType": "poi",
                            "stylers": [
                                {
                                    "saturation": -100
                                },
                                {
                                    "lightness": 51
                                }
                            ]
                        },
                        {
                            "featureType": "road.highway",
                            "stylers": [
                                {
                                    "saturation": -50
                                }
                            ]
                        },
                        {
                            "featureType": "road.arterial",
                            "stylers": [
                                {
                                    "saturation": -20
                                },
                                {
                                    "lightness": 30
                                }
                            ]
                        },
                        {
                            "featureType": "road.local",
                            "stylers": [
                                {
                                    "saturation": -100
                                },
                                {
                                    "lightness": 40
                                },
                                {
                                    "visibility": "on"
                                }
                            ]
                        },
                        {
                            "featureType": "transit",
                            "stylers": [
                                {
                                    "saturation": -100
                                },
                                {
                                    "visibility": "simplified"
                                }
                            ]
                        },
                        {
                            "featureType": "water",
                            "elementType": "labels",
                            "stylers": [
                                {
                                    "visibility": "on"
                                },
                                {
                                    "lightness": -25
                                },
                                {
                                    "saturation": -100
                                }
                            ]
                        },
                        {
                            "featureType": "water",
                            "elementType": "geometry",
                            "stylers": [
                                {
                                    "hue": "#ffff00"
                                },
                                {
                                    "lightness": -25
                                },
                                {
                                    "saturation": -97
                                }
                            ]
                        }
                    ]
                };

            var map = new google.maps.Map(jQuery("#google_map")[0], mappy),
                newpin = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'smartwave/granada/googlemap/'.$_marker_image; ?>';

            new google.maps.Marker({
                position: myLatLng,
                map: map,
                icon: newpin,
                animation: google.maps.Animation.DROP,
                title: 'Granada' // Title for marker
            });

            /* Create new lat and long for label placed little bit down from marker*/
            var labelLatLng = new google.maps.LatLng(<?php echo $_latitude ?>, <?php echo $_longitude ?>),
                mapLabel = new MapLabel({
                    text: 'Granada',
                    position: labelLatLng,
                    map: map,
                    fontSize: 18,
                    align: 'center'
                });

            mapLabel.set('position', labelLatLng);
            mapLabel.set('fontColor', '#57add8');
            mapLabel.set('fontSize', 18);
            mapLabel.set('strokeWeight', 0);
        }

        if (jQuery("#google_map")) {
            google.maps.event.addDomListener(window, 'load', initialize);
        }
    }());

</script>