<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
$_latitude = Mage::getStoreConfig('granada_setting/google_map/latitude', $code);
$_longitude = Mage::getStoreConfig('granada_setting/google_map/longitude', $code);
$_zoom = Mage::getStoreConfig('granada_setting/google_map/zoom', $code);
$_marker_image = Mage::getStoreConfig('granada_setting/google_map/marker_image', $code);
if (!$_marker_image) {
    $_marker_image = 'pin.png';
}
$block_id = Mage::getStoreConfig('granada_setting/contact_us/pop_cms_block', $code);

?>

<div id="google_map_custom"></div>
<script src="//maps.google.com/maps/api/js?sensor=false&amp;v=3.17"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>js/maplabel.js"></script>
<script>
    /*---- Google map -----*/
    (function () {
        "use strict";

        if (jQuery("#google_map_custom")) {
            var locations = [
                ['<?php if ($block_id) {
                    $popup_block = Mage::getModel('cms/block')->load($block_id);
                    if($popup_block->getIsActive()){
                        echo $this->getLayout()->createBlock('cms/block')->setBlockId($block_id)->toHtml();
                    }
                }?>', <?php echo $_latitude ?>, <?php echo $_longitude ?>, 9]
            ];

            var map = new google.maps.Map(jQuery("#google_map_custom")[0], {
                zoom: <?php echo $_zoom ?>,
                center: new google.maps.LatLng(<?php echo $_latitude ?>, <?php echo $_longitude ?>),
                scrollwheel: false,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });

            var infowindow = new google.maps.InfoWindow();


            var marker, i;

            for (i = 0; i < locations.length; i++) {
                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                    map: map,
                    animation: google.maps.Animation.DROP,
                    icon: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'smartwave/granada/googlemap/'.$_marker_image; ?>',
                });

                google.maps.event.addListener(marker, 'click', (function(marker, i) {
                    return function() {
                        infowindow.setContent(locations[i][0]);
                        infowindow.open(map, marker);
                    }
                })(marker, i));
            }
        }
    }());

</script>